### ISSUE TITLE
Esys_Create_Finish() Received TPM Error.

### ISSUE THREAD

**Issue by warusadura** [dnuka/tpmsecret#2]
I'm tying to create a secondary key with call to `Esys_Create()`. But it always ended up with the following error,
```
WARNING:esys:src/tss2-esys/api/Esys_Create.c:375:Esys_Create_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_Create.c:120:Esys_Create() Esys Finish ErrorCode (0x00000184) 
error: Esys_Create!
```

**Comment by warusadura** [comment]
cc @ueno @ansasaki @PeterHuewe @AndreasFuchsSIT

**Comment by AndreasFuchsTPM** [comment]
tpm2_rc_decode helps a lot here:
```
$ tpm2_rc_decode 0x184
tpm:handle(1):value is out of range or is not correct for the context
```

Problem is: You're passing the parameter `pr_handle` by value into `create_primary_key()` here:
https://github.com/dnuka/tpmsecret/blob/ac9705cb2a50b571c31e08fa54c59d0602acfb8a/src/main.c#L27

You need to pass the reference, so that the value is returned from the funciton:
```
int create_primary_key(ESYS_CONTEXT *ctx, ESYS_TR *pr_handle);

ret = create_primary_key(ctx, &pr_handle);
```

**Comment by AndreasFuchsTPM** [comment]
Also you could gdb into your program and set a breakpoint at secondarykey.c:77 and inspect the value of `pr_handle` and you would have seen the incorrect value directly.

**Comment by warusadura** [comment]
Thanks @AndreasFuchsSIT :) I appreciate it.

**Comment by warusadura** [comment]
I'll look into gdb.
